/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
import { PlannedMeal } from "./components/rp-day-slot/rp-day-slot";
import { SelectOption } from "./components/rp-select/rp-select";
export { PlannedMeal } from "./components/rp-day-slot/rp-day-slot";
export { SelectOption } from "./components/rp-select/rp-select";
export namespace Components {
    /**
     * One day column of a weekly meal plan.
     * Meals can be moved by dragging between columns or by choosing a day from the select on
     * each meal. Both paths emit the same `rpMoveMeal`, so a consumer handles one event and
     * gets both. The select is not a fallback that could be dropped later — it is the keyboard
     * and touch path, and dragging is the enhancement layered over it.
     */
    interface RpDaySlot {
        /**
          * Machine-readable day key, echoed in every event. Reflected so a pointer drag can read the target column straight off the element it lands on.
         */
        "day": string;
        /**
          * Human-readable day name shown as the column heading.
          * @default ''
         */
        "dayLabel": string;
        /**
          * Display names for the keys in `days`, as a key-to-label map.  Without this the move control would offer raw keys like "mon". Optional, so a consumer whose keys are already human-readable can leave it unset.
          * @default {}
         */
        "dayLabels": Record<string, string>;
        /**
          * All day keys, used to populate each meal's move target list.
          * @default []
         */
        "days": string[];
        /**
          * Meals planned for this day. Must be assigned as a DOM property.
          * @default []
         */
        "meals": PlannedMeal[];
    }
    /**
     * A single-select row of filter chips.
     * Selecting the active chip clears the filter, so the event detail is nullable —
     * consumers translate null into "remove this search param".
     */
    interface RpFilterChips {
        /**
          * Accessible label for the group.
          * @default 'Filter'
         */
        "label": string;
        /**
          * Available filter values.  An array has no attribute representation, so this must be assigned as a DOM property. Frameworks that set properties on custom elements do this automatically.
          * @default []
         */
        "options": string[];
        /**
          * Currently active value, or null when no filter is applied.
          * @default null
         */
        "selected": string | null;
    }
    /**
     * A collapsed filter control: a pill that opens a tray of options.
     * `rp-filter-chips` renders every option at once, which is right for a handful and wrong
     * for the ~30 categories and cuisines a recipe app has — the chips fill the top of the
     * page before any content appears. This collapses the same single-select behaviour behind
     * one trigger and adds a search field, so a long list stays usable.
     * It emits the same `rpFilterChange` as `rp-filter-chips`, including `null` to clear, so
     * a consumer can swap one for the other without touching its handler.
     */
    interface RpFilterMenu {
        /**
          * Text on the trigger, e.g. "Category".
          * @default 'Filter'
         */
        "label": string;
        /**
          * Whether the tray is open. Reflected so a consumer can style the open state.
          * @default false
         */
        "open": boolean;
        /**
          * Available values. An array has no attribute representation, so this must be assigned as a DOM property.
          * @default []
         */
        "options": string[];
        /**
          * Placeholder for the in-tray search field.
          * @default 'Search…'
         */
        "searchPlaceholder": string;
        /**
          * Hides the search field. Below roughly a dozen options the field costs more attention than the scanning it saves.
          * @default true
         */
        "searchable": boolean;
        /**
          * Currently active value, or null when no filter is applied.
          * @default null
         */
        "selected": string | null;
    }
    /**
     * A measure-and-name ingredient table.
     */
    interface RpIngredientList {
        /**
          * Ingredients to display. Must be assigned as a DOM property, not an attribute.
          * @default []
         */
        "items": Array<{ name: string; measure: string }>;
    }
    /**
     * A modal dialog with a focus trap.
     * Escape and focus containment are handled here rather than left to consumers, because
     * getting them wrong is the usual reason a hand-rolled modal is inaccessible.
     */
    interface RpModal {
        /**
          * Moves focus to the first focusable control inside the dialog.  Exposed as a method because "move focus now" is a one-shot action with no state to represent; a prop would have to be toggled and reset to fire it twice.
         */
        "focusFirstField": () => Promise<void>;
        /**
          * Dialog heading, also used as its accessible name.
          * @default ''
         */
        "heading": string;
        /**
          * Whether the dialog is visible.
          * @default false
         */
        "open": boolean;
    }
    /**
     * A recipe summary tile.
     * Takes only primitives, so it can be driven from plain HTML attributes with no
     * framework present. It has no idea where a recipe comes from or what a route is —
     * consumers inject navigation through the `actions` slot.
     */
    interface RpRecipeCard {
        /**
          * Cuisine or region, shown as a second meta pill when present.
         */
        "area"?: string;
        /**
          * Category label shown under the heading.
         */
        "category"?: string;
        /**
          * Whether this recipe is currently a favorite. Reflected for CSS hooks.
          * @default false
         */
        "favorite": boolean;
        /**
          * Destination for the whole card.  Given one, the card renders a link that covers its full area, so the tile behaves the way a card is expected to: clicking anywhere opens the recipe. The favorite button and anything in the `actions` slot sit above it and keep their own behaviour.  This is still a plain URL, not route knowledge — the component neither builds it nor knows what it points at, so a consumer with no router can pass an ordinary href. Omitting it leaves the card inert, which is what the planner picker wants.
         */
        "href"?: string;
        /**
          * Accessible name for that link. Defaults to the recipe title, which is what a link covering a whole card should announce.
         */
        "hrefLabel"?: string;
        /**
          * Absolute URL of the recipe image.
         */
        "image"?: string;
        /**
          * Preparation time in minutes, shown as a meta pill when present.
         */
        "minutes"?: number;
        /**
          * Identifier echoed back in the toggle event so consumers know which card fired.
         */
        "recipeId": string;
        /**
          * Recipe name, rendered as the card heading.  Named `recipeTitle` rather than `title` because every HTMLElement already defines `title` on its prototype; shadowing it produces inconsistent behaviour across browsers.
         */
        "recipeTitle": string;
    }
    /**
     * A search input that emits on submit rather than on every keystroke.
     * Per-keystroke events would race the consumer's own navigation: each one triggers a
     * server round trip, and a slow response can land after the user has typed more,
     * overwriting the field. Submitting explicitly keeps the interaction deterministic.
     */
    interface RpSearchBar {
        /**
          * Accessible label for the input.
          * @default 'Search recipes'
         */
        "label": string;
        /**
          * Placeholder shown when the field is empty.
          * @default 'Search recipes'
         */
        "placeholder": string;
        /**
          * Initial query text. Changing it externally resets the field.
          * @default ''
         */
        "value": string;
    }
    /**
     * A single-select control with a styled option list.
     * A native `<select>` renders its dropdown as an operating-system panel: square corners, a
     * blue system highlight, and platform typography. None of that is reachable from CSS —
     * `option` accepts a colour and a font at best, and the panel itself accepts nothing — so
     * a native control can never match a designed interface once it is open. On a small screen
     * the panel also breaks out of any dialog it sits in, because it is not part of the page.
     * This renders the list as ordinary elements instead, which is what makes it styleable,
     * and reimplements the keyboard behaviour the native control would have provided:
     * Up/Down/Home/End to move, Enter or Space to commit, Escape to dismiss, and typing a few
     * characters to jump. The trigger carries `role="combobox"` and the list `role="listbox"`,
     * so assistive technology sees the same control it would have seen before.
     */
    interface RpSelect {
        /**
          * Renders a smaller trigger, for a control sitting in a narrow column.  Reflected so the stylesheet can select on it. The list keeps the full type size — it is an overlay and has room even where the trigger does not.
          * @default false
         */
        "compact": boolean;
        /**
          * Disables the control.
          * @default false
         */
        "disabled": boolean;
        /**
          * Set when the list opens upward because there is more room above the trigger.  A prop rather than internal state so it reflects to an attribute the stylesheet can select on; it is written by the component, not by a consumer.
          * @default false
         */
        "dropUp": boolean;
        /**
          * Moves focus to the trigger, so a consumer can direct attention here.
         */
        "focusControl": () => Promise<void>;
        /**
          * Accessible name, used when no external label is associated.
          * @default ''
         */
        "label": string;
        /**
          * Whether the list is open. Reflected so a consumer can style the open state.
          * @default false
         */
        "open": boolean;
        /**
          * Options to choose from. An array has no attribute form; assign it as a property.
          * @default []
         */
        "options": SelectOption[];
        /**
          * Shown on the trigger when nothing is selected.
          * @default 'Choose…'
         */
        "placeholder": string;
        /**
          * Currently selected value.
          * @default ''
         */
        "value": string;
    }
}
export interface RpDaySlotCustomEvent<T> extends CustomEvent<T> {
    detail: T;
    target: HTMLRpDaySlotElement;
}
export interface RpFilterChipsCustomEvent<T> extends CustomEvent<T> {
    detail: T;
    target: HTMLRpFilterChipsElement;
}
export interface RpFilterMenuCustomEvent<T> extends CustomEvent<T> {
    detail: T;
    target: HTMLRpFilterMenuElement;
}
export interface RpModalCustomEvent<T> extends CustomEvent<T> {
    detail: T;
    target: HTMLRpModalElement;
}
export interface RpRecipeCardCustomEvent<T> extends CustomEvent<T> {
    detail: T;
    target: HTMLRpRecipeCardElement;
}
export interface RpSearchBarCustomEvent<T> extends CustomEvent<T> {
    detail: T;
    target: HTMLRpSearchBarElement;
}
export interface RpSelectCustomEvent<T> extends CustomEvent<T> {
    detail: T;
    target: HTMLRpSelectElement;
}
declare global {
    interface HTMLRpDaySlotElementEventMap {
        "rpAddMeal": string;
        "rpRemoveMeal": { id: string; day: string };
        "rpMoveMeal": { id: string; from: string; to: string };
    }
    /**
     * One day column of a weekly meal plan.
     * Meals can be moved by dragging between columns or by choosing a day from the select on
     * each meal. Both paths emit the same `rpMoveMeal`, so a consumer handles one event and
     * gets both. The select is not a fallback that could be dropped later — it is the keyboard
     * and touch path, and dragging is the enhancement layered over it.
     */
    interface HTMLRpDaySlotElement extends Components.RpDaySlot, HTMLStencilElement {
        addEventListener<K extends keyof HTMLRpDaySlotElementEventMap>(type: K, listener: (this: HTMLRpDaySlotElement, ev: RpDaySlotCustomEvent<HTMLRpDaySlotElementEventMap[K]>) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | AddEventListenerOptions): void;
        removeEventListener<K extends keyof HTMLRpDaySlotElementEventMap>(type: K, listener: (this: HTMLRpDaySlotElement, ev: RpDaySlotCustomEvent<HTMLRpDaySlotElementEventMap[K]>) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | EventListenerOptions): void;
    }
    var HTMLRpDaySlotElement: {
        prototype: HTMLRpDaySlotElement;
        new (): HTMLRpDaySlotElement;
    };
    interface HTMLRpFilterChipsElementEventMap {
        "rpFilterChange": string | null;
    }
    /**
     * A single-select row of filter chips.
     * Selecting the active chip clears the filter, so the event detail is nullable —
     * consumers translate null into "remove this search param".
     */
    interface HTMLRpFilterChipsElement extends Components.RpFilterChips, HTMLStencilElement {
        addEventListener<K extends keyof HTMLRpFilterChipsElementEventMap>(type: K, listener: (this: HTMLRpFilterChipsElement, ev: RpFilterChipsCustomEvent<HTMLRpFilterChipsElementEventMap[K]>) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | AddEventListenerOptions): void;
        removeEventListener<K extends keyof HTMLRpFilterChipsElementEventMap>(type: K, listener: (this: HTMLRpFilterChipsElement, ev: RpFilterChipsCustomEvent<HTMLRpFilterChipsElementEventMap[K]>) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | EventListenerOptions): void;
    }
    var HTMLRpFilterChipsElement: {
        prototype: HTMLRpFilterChipsElement;
        new (): HTMLRpFilterChipsElement;
    };
    interface HTMLRpFilterMenuElementEventMap {
        "rpFilterChange": string | null;
        "rpMenuToggle": { label: string; open: boolean };
    }
    /**
     * A collapsed filter control: a pill that opens a tray of options.
     * `rp-filter-chips` renders every option at once, which is right for a handful and wrong
     * for the ~30 categories and cuisines a recipe app has — the chips fill the top of the
     * page before any content appears. This collapses the same single-select behaviour behind
     * one trigger and adds a search field, so a long list stays usable.
     * It emits the same `rpFilterChange` as `rp-filter-chips`, including `null` to clear, so
     * a consumer can swap one for the other without touching its handler.
     */
    interface HTMLRpFilterMenuElement extends Components.RpFilterMenu, HTMLStencilElement {
        addEventListener<K extends keyof HTMLRpFilterMenuElementEventMap>(type: K, listener: (this: HTMLRpFilterMenuElement, ev: RpFilterMenuCustomEvent<HTMLRpFilterMenuElementEventMap[K]>) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | AddEventListenerOptions): void;
        removeEventListener<K extends keyof HTMLRpFilterMenuElementEventMap>(type: K, listener: (this: HTMLRpFilterMenuElement, ev: RpFilterMenuCustomEvent<HTMLRpFilterMenuElementEventMap[K]>) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | EventListenerOptions): void;
    }
    var HTMLRpFilterMenuElement: {
        prototype: HTMLRpFilterMenuElement;
        new (): HTMLRpFilterMenuElement;
    };
    /**
     * A measure-and-name ingredient table.
     */
    interface HTMLRpIngredientListElement extends Components.RpIngredientList, HTMLStencilElement {
    }
    var HTMLRpIngredientListElement: {
        prototype: HTMLRpIngredientListElement;
        new (): HTMLRpIngredientListElement;
    };
    interface HTMLRpModalElementEventMap {
        "rpClose": void;
    }
    /**
     * A modal dialog with a focus trap.
     * Escape and focus containment are handled here rather than left to consumers, because
     * getting them wrong is the usual reason a hand-rolled modal is inaccessible.
     */
    interface HTMLRpModalElement extends Components.RpModal, HTMLStencilElement {
        addEventListener<K extends keyof HTMLRpModalElementEventMap>(type: K, listener: (this: HTMLRpModalElement, ev: RpModalCustomEvent<HTMLRpModalElementEventMap[K]>) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | AddEventListenerOptions): void;
        removeEventListener<K extends keyof HTMLRpModalElementEventMap>(type: K, listener: (this: HTMLRpModalElement, ev: RpModalCustomEvent<HTMLRpModalElementEventMap[K]>) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | EventListenerOptions): void;
    }
    var HTMLRpModalElement: {
        prototype: HTMLRpModalElement;
        new (): HTMLRpModalElement;
    };
    interface HTMLRpRecipeCardElementEventMap {
        "rpFavoriteToggle": { recipeId: string; favorite: boolean };
    }
    /**
     * A recipe summary tile.
     * Takes only primitives, so it can be driven from plain HTML attributes with no
     * framework present. It has no idea where a recipe comes from or what a route is —
     * consumers inject navigation through the `actions` slot.
     */
    interface HTMLRpRecipeCardElement extends Components.RpRecipeCard, HTMLStencilElement {
        addEventListener<K extends keyof HTMLRpRecipeCardElementEventMap>(type: K, listener: (this: HTMLRpRecipeCardElement, ev: RpRecipeCardCustomEvent<HTMLRpRecipeCardElementEventMap[K]>) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | AddEventListenerOptions): void;
        removeEventListener<K extends keyof HTMLRpRecipeCardElementEventMap>(type: K, listener: (this: HTMLRpRecipeCardElement, ev: RpRecipeCardCustomEvent<HTMLRpRecipeCardElementEventMap[K]>) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | EventListenerOptions): void;
    }
    var HTMLRpRecipeCardElement: {
        prototype: HTMLRpRecipeCardElement;
        new (): HTMLRpRecipeCardElement;
    };
    interface HTMLRpSearchBarElementEventMap {
        "rpSearch": string;
        "rpClear": void;
    }
    /**
     * A search input that emits on submit rather than on every keystroke.
     * Per-keystroke events would race the consumer's own navigation: each one triggers a
     * server round trip, and a slow response can land after the user has typed more,
     * overwriting the field. Submitting explicitly keeps the interaction deterministic.
     */
    interface HTMLRpSearchBarElement extends Components.RpSearchBar, HTMLStencilElement {
        addEventListener<K extends keyof HTMLRpSearchBarElementEventMap>(type: K, listener: (this: HTMLRpSearchBarElement, ev: RpSearchBarCustomEvent<HTMLRpSearchBarElementEventMap[K]>) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | AddEventListenerOptions): void;
        removeEventListener<K extends keyof HTMLRpSearchBarElementEventMap>(type: K, listener: (this: HTMLRpSearchBarElement, ev: RpSearchBarCustomEvent<HTMLRpSearchBarElementEventMap[K]>) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | EventListenerOptions): void;
    }
    var HTMLRpSearchBarElement: {
        prototype: HTMLRpSearchBarElement;
        new (): HTMLRpSearchBarElement;
    };
    interface HTMLRpSelectElementEventMap {
        "rpSelectChange": string;
    }
    /**
     * A single-select control with a styled option list.
     * A native `<select>` renders its dropdown as an operating-system panel: square corners, a
     * blue system highlight, and platform typography. None of that is reachable from CSS —
     * `option` accepts a colour and a font at best, and the panel itself accepts nothing — so
     * a native control can never match a designed interface once it is open. On a small screen
     * the panel also breaks out of any dialog it sits in, because it is not part of the page.
     * This renders the list as ordinary elements instead, which is what makes it styleable,
     * and reimplements the keyboard behaviour the native control would have provided:
     * Up/Down/Home/End to move, Enter or Space to commit, Escape to dismiss, and typing a few
     * characters to jump. The trigger carries `role="combobox"` and the list `role="listbox"`,
     * so assistive technology sees the same control it would have seen before.
     */
    interface HTMLRpSelectElement extends Components.RpSelect, HTMLStencilElement {
        addEventListener<K extends keyof HTMLRpSelectElementEventMap>(type: K, listener: (this: HTMLRpSelectElement, ev: RpSelectCustomEvent<HTMLRpSelectElementEventMap[K]>) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | AddEventListenerOptions): void;
        removeEventListener<K extends keyof HTMLRpSelectElementEventMap>(type: K, listener: (this: HTMLRpSelectElement, ev: RpSelectCustomEvent<HTMLRpSelectElementEventMap[K]>) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | EventListenerOptions): void;
    }
    var HTMLRpSelectElement: {
        prototype: HTMLRpSelectElement;
        new (): HTMLRpSelectElement;
    };
    interface HTMLElementTagNameMap {
        "rp-day-slot": HTMLRpDaySlotElement;
        "rp-filter-chips": HTMLRpFilterChipsElement;
        "rp-filter-menu": HTMLRpFilterMenuElement;
        "rp-ingredient-list": HTMLRpIngredientListElement;
        "rp-modal": HTMLRpModalElement;
        "rp-recipe-card": HTMLRpRecipeCardElement;
        "rp-search-bar": HTMLRpSearchBarElement;
        "rp-select": HTMLRpSelectElement;
    }
}
declare namespace LocalJSX {
    type OneOf<K extends string, PropT, AttrT = PropT> = { [P in K]: PropT } & { [P in `attr:${K}`]?: never } | { [P in `attr:${K}`]: AttrT } & { [P in K]?: never };

    /**
     * One day column of a weekly meal plan.
     * Meals can be moved by dragging between columns or by choosing a day from the select on
     * each meal. Both paths emit the same `rpMoveMeal`, so a consumer handles one event and
     * gets both. The select is not a fallback that could be dropped later — it is the keyboard
     * and touch path, and dragging is the enhancement layered over it.
     */
    interface RpDaySlot {
        /**
          * Machine-readable day key, echoed in every event. Reflected so a pointer drag can read the target column straight off the element it lands on.
         */
        "day": string;
        /**
          * Human-readable day name shown as the column heading.
          * @default ''
         */
        "dayLabel"?: string;
        /**
          * Display names for the keys in `days`, as a key-to-label map.  Without this the move control would offer raw keys like "mon". Optional, so a consumer whose keys are already human-readable can leave it unset.
          * @default {}
         */
        "dayLabels"?: Record<string, string>;
        /**
          * All day keys, used to populate each meal's move target list.
          * @default []
         */
        "days"?: string[];
        /**
          * Meals planned for this day. Must be assigned as a DOM property.
          * @default []
         */
        "meals"?: PlannedMeal[];
        /**
          * Fired when the user asks to add a meal to this day.
         */
        "onRpAddMeal"?: (event: RpDaySlotCustomEvent<string>) => void;
        /**
          * Fired when a meal is reassigned to a different day, by drag or by select.
         */
        "onRpMoveMeal"?: (event: RpDaySlotCustomEvent<{ id: string; from: string; to: string }>) => void;
        /**
          * Fired when a meal is removed from this day.
         */
        "onRpRemoveMeal"?: (event: RpDaySlotCustomEvent<{ id: string; day: string }>) => void;
    }
    /**
     * A single-select row of filter chips.
     * Selecting the active chip clears the filter, so the event detail is nullable —
     * consumers translate null into "remove this search param".
     */
    interface RpFilterChips {
        /**
          * Accessible label for the group.
          * @default 'Filter'
         */
        "label"?: string;
        /**
          * Fired with the new selection, or null when the filter is cleared.
         */
        "onRpFilterChange"?: (event: RpFilterChipsCustomEvent<string | null>) => void;
        /**
          * Available filter values.  An array has no attribute representation, so this must be assigned as a DOM property. Frameworks that set properties on custom elements do this automatically.
          * @default []
         */
        "options"?: string[];
        /**
          * Currently active value, or null when no filter is applied.
          * @default null
         */
        "selected"?: string | null;
    }
    /**
     * A collapsed filter control: a pill that opens a tray of options.
     * `rp-filter-chips` renders every option at once, which is right for a handful and wrong
     * for the ~30 categories and cuisines a recipe app has — the chips fill the top of the
     * page before any content appears. This collapses the same single-select behaviour behind
     * one trigger and adds a search field, so a long list stays usable.
     * It emits the same `rpFilterChange` as `rp-filter-chips`, including `null` to clear, so
     * a consumer can swap one for the other without touching its handler.
     */
    interface RpFilterMenu {
        /**
          * Text on the trigger, e.g. "Category".
          * @default 'Filter'
         */
        "label"?: string;
        /**
          * Fired with the new selection, or null when the filter is cleared.
         */
        "onRpFilterChange"?: (event: RpFilterMenuCustomEvent<string | null>) => void;
        /**
          * Fired when the tray opens or closes, so a consumer can coordinate two menus.
         */
        "onRpMenuToggle"?: (event: RpFilterMenuCustomEvent<{ label: string; open: boolean }>) => void;
        /**
          * Whether the tray is open. Reflected so a consumer can style the open state.
          * @default false
         */
        "open"?: boolean;
        /**
          * Available values. An array has no attribute representation, so this must be assigned as a DOM property.
          * @default []
         */
        "options"?: string[];
        /**
          * Placeholder for the in-tray search field.
          * @default 'Search…'
         */
        "searchPlaceholder"?: string;
        /**
          * Hides the search field. Below roughly a dozen options the field costs more attention than the scanning it saves.
          * @default true
         */
        "searchable"?: boolean;
        /**
          * Currently active value, or null when no filter is applied.
          * @default null
         */
        "selected"?: string | null;
    }
    /**
     * A measure-and-name ingredient table.
     */
    interface RpIngredientList {
        /**
          * Ingredients to display. Must be assigned as a DOM property, not an attribute.
          * @default []
         */
        "items"?: Array<{ name: string; measure: string }>;
    }
    /**
     * A modal dialog with a focus trap.
     * Escape and focus containment are handled here rather than left to consumers, because
     * getting them wrong is the usual reason a hand-rolled modal is inaccessible.
     */
    interface RpModal {
        /**
          * Dialog heading, also used as its accessible name.
          * @default ''
         */
        "heading"?: string;
        /**
          * Fired when the user dismisses the dialog via Escape, the backdrop, or the close button.
         */
        "onRpClose"?: (event: RpModalCustomEvent<void>) => void;
        /**
          * Whether the dialog is visible.
          * @default false
         */
        "open"?: boolean;
    }
    /**
     * A recipe summary tile.
     * Takes only primitives, so it can be driven from plain HTML attributes with no
     * framework present. It has no idea where a recipe comes from or what a route is —
     * consumers inject navigation through the `actions` slot.
     */
    interface RpRecipeCard {
        /**
          * Cuisine or region, shown as a second meta pill when present.
         */
        "area"?: string;
        /**
          * Category label shown under the heading.
         */
        "category"?: string;
        /**
          * Whether this recipe is currently a favorite. Reflected for CSS hooks.
          * @default false
         */
        "favorite"?: boolean;
        /**
          * Destination for the whole card.  Given one, the card renders a link that covers its full area, so the tile behaves the way a card is expected to: clicking anywhere opens the recipe. The favorite button and anything in the `actions` slot sit above it and keep their own behaviour.  This is still a plain URL, not route knowledge — the component neither builds it nor knows what it points at, so a consumer with no router can pass an ordinary href. Omitting it leaves the card inert, which is what the planner picker wants.
         */
        "href"?: string;
        /**
          * Accessible name for that link. Defaults to the recipe title, which is what a link covering a whole card should announce.
         */
        "hrefLabel"?: string;
        /**
          * Absolute URL of the recipe image.
         */
        "image"?: string;
        /**
          * Preparation time in minutes, shown as a meta pill when present.
         */
        "minutes"?: number;
        /**
          * Fired when the favorite control is activated.
         */
        "onRpFavoriteToggle"?: (event: RpRecipeCardCustomEvent<{ recipeId: string; favorite: boolean }>) => void;
        /**
          * Identifier echoed back in the toggle event so consumers know which card fired.
         */
        "recipeId": string;
        /**
          * Recipe name, rendered as the card heading.  Named `recipeTitle` rather than `title` because every HTMLElement already defines `title` on its prototype; shadowing it produces inconsistent behaviour across browsers.
         */
        "recipeTitle": string;
    }
    /**
     * A search input that emits on submit rather than on every keystroke.
     * Per-keystroke events would race the consumer's own navigation: each one triggers a
     * server round trip, and a slow response can land after the user has typed more,
     * overwriting the field. Submitting explicitly keeps the interaction deterministic.
     */
    interface RpSearchBar {
        /**
          * Accessible label for the input.
          * @default 'Search recipes'
         */
        "label"?: string;
        /**
          * Fired when the user clears a non-empty field.
         */
        "onRpClear"?: (event: RpSearchBarCustomEvent<void>) => void;
        /**
          * Fired on submit with the trimmed query.
         */
        "onRpSearch"?: (event: RpSearchBarCustomEvent<string>) => void;
        /**
          * Placeholder shown when the field is empty.
          * @default 'Search recipes'
         */
        "placeholder"?: string;
        /**
          * Initial query text. Changing it externally resets the field.
          * @default ''
         */
        "value"?: string;
    }
    /**
     * A single-select control with a styled option list.
     * A native `<select>` renders its dropdown as an operating-system panel: square corners, a
     * blue system highlight, and platform typography. None of that is reachable from CSS —
     * `option` accepts a colour and a font at best, and the panel itself accepts nothing — so
     * a native control can never match a designed interface once it is open. On a small screen
     * the panel also breaks out of any dialog it sits in, because it is not part of the page.
     * This renders the list as ordinary elements instead, which is what makes it styleable,
     * and reimplements the keyboard behaviour the native control would have provided:
     * Up/Down/Home/End to move, Enter or Space to commit, Escape to dismiss, and typing a few
     * characters to jump. The trigger carries `role="combobox"` and the list `role="listbox"`,
     * so assistive technology sees the same control it would have seen before.
     */
    interface RpSelect {
        /**
          * Renders a smaller trigger, for a control sitting in a narrow column.  Reflected so the stylesheet can select on it. The list keeps the full type size — it is an overlay and has room even where the trigger does not.
          * @default false
         */
        "compact"?: boolean;
        /**
          * Disables the control.
          * @default false
         */
        "disabled"?: boolean;
        /**
          * Set when the list opens upward because there is more room above the trigger.  A prop rather than internal state so it reflects to an attribute the stylesheet can select on; it is written by the component, not by a consumer.
          * @default false
         */
        "dropUp"?: boolean;
        /**
          * Accessible name, used when no external label is associated.
          * @default ''
         */
        "label"?: string;
        /**
          * Fired when a value is chosen.
         */
        "onRpSelectChange"?: (event: RpSelectCustomEvent<string>) => void;
        /**
          * Whether the list is open. Reflected so a consumer can style the open state.
          * @default false
         */
        "open"?: boolean;
        /**
          * Options to choose from. An array has no attribute form; assign it as a property.
          * @default []
         */
        "options"?: SelectOption[];
        /**
          * Shown on the trigger when nothing is selected.
          * @default 'Choose…'
         */
        "placeholder"?: string;
        /**
          * Currently selected value.
          * @default ''
         */
        "value"?: string;
    }

    interface RpDaySlotAttributes {
        "day": string;
        "dayLabel": string;
    }
    interface RpFilterChipsAttributes {
        "selected": string | null;
        "label": string;
    }
    interface RpFilterMenuAttributes {
        "label": string;
        "selected": string | null;
        "searchPlaceholder": string;
        "searchable": boolean;
        "open": boolean;
    }
    interface RpModalAttributes {
        "open": boolean;
        "heading": string;
    }
    interface RpRecipeCardAttributes {
        "recipeId": string;
        "recipeTitle": string;
        "image": string;
        "category": string;
        "href": string;
        "hrefLabel": string;
        "area": string;
        "minutes": number;
        "favorite": boolean;
    }
    interface RpSearchBarAttributes {
        "value": string;
        "placeholder": string;
        "label": string;
    }
    interface RpSelectAttributes {
        "value": string;
        "label": string;
        "placeholder": string;
        "open": boolean;
        "disabled": boolean;
        "compact": boolean;
        "dropUp": boolean;
    }

    interface IntrinsicElements {
        "rp-day-slot": Omit<RpDaySlot, keyof RpDaySlotAttributes> & { [K in keyof RpDaySlot & keyof RpDaySlotAttributes]?: RpDaySlot[K] } & { [K in keyof RpDaySlot & keyof RpDaySlotAttributes as `attr:${K}`]?: RpDaySlotAttributes[K] } & { [K in keyof RpDaySlot & keyof RpDaySlotAttributes as `prop:${K}`]?: RpDaySlot[K] } & OneOf<"day", RpDaySlot["day"], RpDaySlotAttributes["day"]>;
        "rp-filter-chips": Omit<RpFilterChips, keyof RpFilterChipsAttributes> & { [K in keyof RpFilterChips & keyof RpFilterChipsAttributes]?: RpFilterChips[K] } & { [K in keyof RpFilterChips & keyof RpFilterChipsAttributes as `attr:${K}`]?: RpFilterChipsAttributes[K] } & { [K in keyof RpFilterChips & keyof RpFilterChipsAttributes as `prop:${K}`]?: RpFilterChips[K] };
        "rp-filter-menu": Omit<RpFilterMenu, keyof RpFilterMenuAttributes> & { [K in keyof RpFilterMenu & keyof RpFilterMenuAttributes]?: RpFilterMenu[K] } & { [K in keyof RpFilterMenu & keyof RpFilterMenuAttributes as `attr:${K}`]?: RpFilterMenuAttributes[K] } & { [K in keyof RpFilterMenu & keyof RpFilterMenuAttributes as `prop:${K}`]?: RpFilterMenu[K] };
        "rp-ingredient-list": RpIngredientList;
        "rp-modal": Omit<RpModal, keyof RpModalAttributes> & { [K in keyof RpModal & keyof RpModalAttributes]?: RpModal[K] } & { [K in keyof RpModal & keyof RpModalAttributes as `attr:${K}`]?: RpModalAttributes[K] } & { [K in keyof RpModal & keyof RpModalAttributes as `prop:${K}`]?: RpModal[K] };
        "rp-recipe-card": Omit<RpRecipeCard, keyof RpRecipeCardAttributes> & { [K in keyof RpRecipeCard & keyof RpRecipeCardAttributes]?: RpRecipeCard[K] } & { [K in keyof RpRecipeCard & keyof RpRecipeCardAttributes as `attr:${K}`]?: RpRecipeCardAttributes[K] } & { [K in keyof RpRecipeCard & keyof RpRecipeCardAttributes as `prop:${K}`]?: RpRecipeCard[K] } & OneOf<"recipeId", RpRecipeCard["recipeId"], RpRecipeCardAttributes["recipeId"]> & OneOf<"recipeTitle", RpRecipeCard["recipeTitle"], RpRecipeCardAttributes["recipeTitle"]>;
        "rp-search-bar": Omit<RpSearchBar, keyof RpSearchBarAttributes> & { [K in keyof RpSearchBar & keyof RpSearchBarAttributes]?: RpSearchBar[K] } & { [K in keyof RpSearchBar & keyof RpSearchBarAttributes as `attr:${K}`]?: RpSearchBarAttributes[K] } & { [K in keyof RpSearchBar & keyof RpSearchBarAttributes as `prop:${K}`]?: RpSearchBar[K] };
        "rp-select": Omit<RpSelect, keyof RpSelectAttributes> & { [K in keyof RpSelect & keyof RpSelectAttributes]?: RpSelect[K] } & { [K in keyof RpSelect & keyof RpSelectAttributes as `attr:${K}`]?: RpSelectAttributes[K] } & { [K in keyof RpSelect & keyof RpSelectAttributes as `prop:${K}`]?: RpSelect[K] };
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            /**
             * One day column of a weekly meal plan.
             * Meals can be moved by dragging between columns or by choosing a day from the select on
             * each meal. Both paths emit the same `rpMoveMeal`, so a consumer handles one event and
             * gets both. The select is not a fallback that could be dropped later — it is the keyboard
             * and touch path, and dragging is the enhancement layered over it.
             */
            "rp-day-slot": LocalJSX.IntrinsicElements["rp-day-slot"] & JSXBase.HTMLAttributes<HTMLRpDaySlotElement>;
            /**
             * A single-select row of filter chips.
             * Selecting the active chip clears the filter, so the event detail is nullable —
             * consumers translate null into "remove this search param".
             */
            "rp-filter-chips": LocalJSX.IntrinsicElements["rp-filter-chips"] & JSXBase.HTMLAttributes<HTMLRpFilterChipsElement>;
            /**
             * A collapsed filter control: a pill that opens a tray of options.
             * `rp-filter-chips` renders every option at once, which is right for a handful and wrong
             * for the ~30 categories and cuisines a recipe app has — the chips fill the top of the
             * page before any content appears. This collapses the same single-select behaviour behind
             * one trigger and adds a search field, so a long list stays usable.
             * It emits the same `rpFilterChange` as `rp-filter-chips`, including `null` to clear, so
             * a consumer can swap one for the other without touching its handler.
             */
            "rp-filter-menu": LocalJSX.IntrinsicElements["rp-filter-menu"] & JSXBase.HTMLAttributes<HTMLRpFilterMenuElement>;
            /**
             * A measure-and-name ingredient table.
             */
            "rp-ingredient-list": LocalJSX.IntrinsicElements["rp-ingredient-list"] & JSXBase.HTMLAttributes<HTMLRpIngredientListElement>;
            /**
             * A modal dialog with a focus trap.
             * Escape and focus containment are handled here rather than left to consumers, because
             * getting them wrong is the usual reason a hand-rolled modal is inaccessible.
             */
            "rp-modal": LocalJSX.IntrinsicElements["rp-modal"] & JSXBase.HTMLAttributes<HTMLRpModalElement>;
            /**
             * A recipe summary tile.
             * Takes only primitives, so it can be driven from plain HTML attributes with no
             * framework present. It has no idea where a recipe comes from or what a route is —
             * consumers inject navigation through the `actions` slot.
             */
            "rp-recipe-card": LocalJSX.IntrinsicElements["rp-recipe-card"] & JSXBase.HTMLAttributes<HTMLRpRecipeCardElement>;
            /**
             * A search input that emits on submit rather than on every keystroke.
             * Per-keystroke events would race the consumer's own navigation: each one triggers a
             * server round trip, and a slow response can land after the user has typed more,
             * overwriting the field. Submitting explicitly keeps the interaction deterministic.
             */
            "rp-search-bar": LocalJSX.IntrinsicElements["rp-search-bar"] & JSXBase.HTMLAttributes<HTMLRpSearchBarElement>;
            /**
             * A single-select control with a styled option list.
             * A native `<select>` renders its dropdown as an operating-system panel: square corners, a
             * blue system highlight, and platform typography. None of that is reachable from CSS —
             * `option` accepts a colour and a font at best, and the panel itself accepts nothing — so
             * a native control can never match a designed interface once it is open. On a small screen
             * the panel also breaks out of any dialog it sits in, because it is not part of the page.
             * This renders the list as ordinary elements instead, which is what makes it styleable,
             * and reimplements the keyboard behaviour the native control would have provided:
             * Up/Down/Home/End to move, Enter or Space to commit, Escape to dismiss, and typing a few
             * characters to jump. The trigger carries `role="combobox"` and the list `role="listbox"`,
             * so assistive technology sees the same control it would have seen before.
             */
            "rp-select": LocalJSX.IntrinsicElements["rp-select"] & JSXBase.HTMLAttributes<HTMLRpSelectElement>;
        }
    }
}
